name: rental_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1      # state management
  go_router: ^13.0.0            # navigation
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  flutter_paystack_plus: ^2.5.0 # Paystack payment gateway
  fpdart: ^1.1.0                # Functional programming utilities

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
